export const ValidationMessage = {
  FULL_NAME_REQUIRED: "Full name field is required.",
  EMAIL_REQUIRED: "Email address field is required.",
  PASSWORD_REQUIRED: "Password field is required.",
  PASSWORD_VALID:
    "Password must has at least 8 characters that include at least 1 lowercase character, 1 uppercase characters, 1 number, and 1 special character in (!@#$%^&*)",
  NEW_PASSWORD_VALID: "New password field is required.",
  CONFIRM_NEW_PASSWORD_VALID: "Confirm new password field is required.",
  CONFIRM_PASSWORD_VALID: "New password and confirm password doesn't match.",
  CONFIRM_PASSWORD_VALID_NEW: "Password and confirm password doesn't match.",
  CONFIRM_PASSWORD: "Password and confirm password doesn't match.",
  ENTER_VALID_EMAIL: "Please enter valid email.",
  FIRST_NAME_REQUIRED: "First name field is required.",
  FIRST_NAME_MIN_LENGTH: "First Name must be at least 1 character.",
  FIRST_NAME_MAX_LENGTH: "First Name cannot exceed 50 characters.",
  TITLE_MAX_LENGTH: "Title cannot exceed 100 characters.",
  SUMMARY_REQUIRED: "summary is required.",
  LAST_NAME_REQUIRED: "last name field is required.",
  LAST_NAME_MIN_LENGTH: "Last Name must be at least 1 character.",
  LAST_NAME_MAX_LENGTH: "Last Name cannot exceed 50 characters.",
  VALID_MOBILE_NO: "Please enter a valid mobile number.",
  MOBILE_NOT_LESS_10: "Mobile number must be at least 10 digits.",
  MOBILE_NOT_GRATER_15: "Mobile number cannot exceed 15 digits.",
  MOBILE_NUMBER_REQUIRED: "Mobile no field is required.",
  INDUSTRY_NAME_REQUIRED: "Business name field is required.",
  INDUSTRY_Type_REQUIRED: "Select industry type.",
  ZIP_CODE_FIELD: "Zipcode field is required.",
  OTP_REQUIRED: "OTP field is required.",
  OTP_INVALID: "Please enter valid otp.",
  ROLE_REQUIRED: "Please select role.",
  TIME_ZONE_REQUIRED: "Please select timezone.",
  CARD_NO_REQUIRED: "Card no field is required.",
  EXPIRE_DATE_REQUIRED: "Expiry date field is required.",
  CVV_REQUIRED: "Expiry date field is required.",
  CARD_HOLDER_NAME_REQUIRED: "Card holder field is required.",
  BUSINESS_NAME_REQUIRED: "Business name field is required.",
  ROLE_REQUIRED_FIELD: "Role field is required.",
  STATUS_REQUIRED: "Status field is required.",
  USER_NAME_REQUIRED: "User name field is required.",
  MANUFACTURER_REQUIRED: "Manufacturer name field is required.",
  LEAD_OWNER_REQUIRED: "Lead owner field is required.",
  LEAD_ASSISTANT_REQUIRED: "Lead assistant field is required.",
  PHONE_REQUIRED: "Phone no field is required.",
  VALID_URL: "Please enter valid url.",
  Lead_Name_REQUIRED: "Lead name field is required.",
  INTERNAL_NOTES_REQUIRED: "Internal notes field is required.",
};
